# Author.create!([
#   {first_name: "J.K.", last_name: "Rowling", biography: "Joanne Rowling is a British novelist, philanthropist, film producer, television producer and screenwriter, best known for writing the Harry Potter fantasy series. The books have won multiple awards, and sold more than 500 million copies,[2] becoming the best-selling book series in history.[3] They have also been the basis for a film series, over which Rowling had overall approval on the scripts[4] and was a producer on the final films in the series."},
#   {first_name: "Nora", last_name: "Ephron", biography: "Nora Ephron was an American journalist, film director, producer, screenwriter, novelist, and blogger. She was best known for her romantic comedies and is a triple nominee for the Academy Award for Writing Original Screenplay; for Silkwood, When Harry Met Sally... and Sleepless in Seattle. She sometimes wrote with her sister, Delia Ephron."}
# ])
# Book.create!([
#   {title: "Harry Potter and the Sorcerer's Stone", author_id: 1, summary: "Harry Potter's life is miserable. His parents are dead and he's stuck with his heartless relatives, who force him to live in a tiny closet under the stairs. But his fortune changes when he receives a letter that tells him the truth about himself: he's a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry. After a lifetime of bottling up his magical powers, Harry finally feels like a normal kid. But even within the Wizarding community, he is special. He is the boy who lived: the only person to have ever survived a killing curse inflicted by the evil Lord Voldemort, who launched a brutal takeover of the Wizarding world, only to vanish after failing to kill Harry. Though Harry's first year at Hogwarts is the best of his life, not everything is perfect. There is a dangerous secret object hidden within the castle walls, and Harry believes it's his responsibility to prevent it from falling into evil hands. But doing so will bring him into contact with forces more terrifying than he ever could have imagined.", genre: "fiction"},
#   {title: "Harry Potter and the Chamber of Secrets", author_id: 1, summary: "The Dursleys were so mean and hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he's packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike. And strike it does. For in Harry's second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor, Gilderoy Lockhart, a spirit named Moaning Myrtle who haunts the girls' bathroom, and the unwanted attentions of Ron Weasley's younger sister, Ginny. But each of these seem minor annoyances when the real trouble begins, and someone -- or something -- starts turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possibly be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects . . . Harry Potter himself?", genre: "fiction"},
#   {title: "Heartburn", author_id: 2, summary: "Is it possible to write a sidesplitting novel about the breakup of the perfect marriage? If the writer is Nora Ephron, the answer is a resounding yes. For in this inspired confection of adultery, revenge, group therapy, and pot roast, the creator of Sleepless in Seattle reminds us that comedy depends on anguish as surely as a proper gravy depends on flour and butter. Seven months into her pregnancy, Rachel Samstat discovers that her husband, Mark, is in love with another woman. The fact that the other woman has \"a neck as long as an arm and a nose as long as a thumb and you should see her legs\" is no consolation. Food sometimes is, though, since Rachel writes cookbooks for a living. And in between trying to win Mark back and loudly wishing him dead, Ephron's irrepressible heroine offers some of her favorite recipes. Heartburn is a sinfully delicious novel, as soul-satisfying as mashed potatoes and as airy as a perfect soufflé. ", genre: "fiction"},
#   {title: "I Remember Nothing: and Other Reflections", author_id: 2, summary: "Nora Ephron returns with her first book since the astounding success of I Feel Bad About My Neck, taking a cool, hard, hilarious look at the past, the present, and the future, bemoaning the vicissitudes of modern life, and recalling with her signature clarity and wisdom everything she hasn’t (yet) forgotten. Ephron writes about falling hard for a way of life (“Journalism: A Love Story”) and about breaking up even harder with the men in her life (“The D Word”); lists “Twenty-five Things People Have a Shocking Capacity to Be Surprised by Over and Over Again” (“There is no explaining the stock market but people try”; “You can never know the truth of anyone’s marriage, including your own”; “Cary Grant was Jewish”; “Men cheat”); reveals the alarming evolution, a decade after she wrote and directed You’ve Got Mail, of her relationship with her in-box (“The Six Stages of E-Mail”); and asks the age-old question, which came first, the chicken soup or the cold? All the while, she gives candid, edgy voice to everything women who have reached a certain age have been thinking . . . but rarely acknowledging. Filled with insights and observations that instantly ring true—and could have come only from Nora Ephron—I Remember Nothing is pure joy. ", genre: "non_fiction"}
# ])
# Inventory.create!([
#   {user_id: 2, book_id: 1, status: "read"},
#   {user_id: 2, book_id: 2, status: "currently_reading"},
#   {user_id: 2, book_id: 3, status: "want_to_read"},
#   {user_id: 2, book_id: 5, status: "read"},
#   {user_id: 1, book_id: 1, status: "read"},
#   {user_id: 1, book_id: 2, status: "want_to_read"}
# ])
# User.create!([
#   {first_name: "Anjelica", last_name: "Towner", email: "towner@gmail.com", password_digest: "$2a$10$0mLLPFdHLIHd8olyPTMde.31kHDCf.psUUWKqcKfFAepEUsQajHIi"},
#   {first_name: "Rory", last_name: "Gilmore", email: "gilmore@gmail.com", password_digest: "$2a$10$knAvbh/mcT1.R8cn3mVB/elxL3nSD.CzPu0lEGawgsCWJJBqGxQai"}
# ])
